apiVersion: v1
kind: Pod
metadata:
  name: efs-app
  labels:
    name: efs-app
spec:
  containers:
  - name: efs-app
    image: centos
    command:
      - "/bin/bash"
    args:
      - "-c"
      - "while true; do echo $(date -u) >> /data/out.txt; sleep 2; done"
    
