apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: astuto-app
  namespace: argocd
spec:
  destination:
    namespace: astuto
    server: https://kubernetes.default.svc
  project: default
  source:
    path: astuto-web-app
    repoURL: https://github.com/kaushikkishore/k8s-deployment.git
    targetRevision: HEAD
  syncPolicy:
    syncOptions:
      - CreateNamespace=true 