apiVersion: apps/v1
kind: Deployment
metadata:
  name: astuto-deployment
  namespace: astuto
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: astuto-web
  template:
    metadata:
      labels:
        app: astuto-web
    spec:
      containers:
      - name: astuto-web-app
        image: kaushikkishore/astuto-web-app:102b628
        envFrom:
          - secretRef:
              name: astuto-secret
        ports:
        - containerPort: 8080
          name: http-app-port
          hostPort: 8080
        livenessProbe:
          httpGet:
            path: /ping
            port: http-app-port
          initialDelaySeconds: 30
          periodSeconds: 30
