apiVersion: v1
kind: Service
metadata:
  name: astuto-service
  namespace: astuto
spec:
  selector:
    app: astuto-web
  ports:
    - protocol: TCP
      port: 80     # The port on the service
      targetPort: 8080  # The port on the pods
  type: LoadBalancer   # Expose the service as a LoadBalancer